import fs from "node:fs";
import path from "node:path";
import { BillDetail } from "./bill-detail";

// The static export needs every bill's page pre-rendered. The list of ids comes
// from the JSON generated by `backend/export_static.py` (not present on a fresh
// clone — return nothing and let `next dev` fall back to dynamic rendering).
export function generateStaticParams() {
  try {
    const file = path.join(process.cwd(), "public", "data", "bills.json");
    const bills = JSON.parse(fs.readFileSync(file, "utf8")) as { id: string }[];
    return bills.map((bill) => ({ id: bill.id }));
  } catch {
    return [];
  }
}

export default async function BillDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  return <BillDetail id={id} />;
}
